Repository eric-rao/WRO-Future-Engineers-2025, pull requests merged in 2025-07, with the labels that each got.

#5 fixed hopefully
  src/testing-structure-nodes/real/CMakeLists.txt
  src/testing-structure-nodes/real/control.py
  src/testing-structure-nodes/real/nagivate.py
Labels: bug, code

#2 camera tweeks
  src/testing-structure-nodes/cameratest.py
  src/testing-structure-nodes/hsvrange.py
  src/testing-structure-nodes/real/LED_node.py
  src/testing-structure-nodes/real/cameraobstacle.py
  src/testing-structure-nodes/real/cameraopen.py
  src/testing-structure-nodes/real/navigateopen.py
  src/testing-structure-nodes/real/ros_robot_controller_SDK.py
  src/testing-structure-nodes/values.py
Labels: general, code

#8 Mdae Schematic with lidar
  schemes/Schematic WRO FE 2025.png
Labels: documentation
